# Generated by Django 2.2.2 on 2019-08-21 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_auto_20190821_0133'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserTable',
            new_name='UserName',
        ),
    ]
